#The gradle.properties file
#Gradle properties, System properties, and Project properties can be found in the gradle.properties file
# https://docs.gradle.org/current/userguide/build_environment.html#the_gradle_properties_file

#Gradle properties(\u4EE5\u201Corg.gradle\u201D\u4E3A\u524D\u7F00):Properties that configure Gradle settings and the Java process that executes your build
# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true

#System properties(\u4EE5\u201CsystemProp\u201D\u4E3A\u524D\u7F00):Properties that are passed to the Gradle runtime (JVM)

#Project properties(\u81EA\u5B9A\u4E49):Properties specific to your Gradle project
#  Project properties can be retrieved lazily using providers.gradleProperty() in build files
# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency=false
pluginGroup=me.watermelon
# SemVer format -> https://semver.org
pluginVersion=1.0
# \u7528\u4E8E\u6539\u53D8\u4F7F\u7528\u7684gradle\u7248\u672C\uFF08\u6784\u5EFA\u4EFB\u52A1\u91CC\u4F7F\u7528\uFF0C\u4EE5\u4E0B\u7684\u5F88\u591A\u5C5E\u6027\u90FD\u662F\u8FD9\u4E2A\u60C5\u51B5\uFF09
gradleVersion=6.0
# Plugin Dependencies(\u8FD8\u9700\u5728plugin.xml\u4E2D\u58F0\u660Edepends) -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
platformPlugins=
platformBundledPlugins=Git4Idea,com.intellij.java
# IntelliJ Platform Properties(Target IDE Platform and Version)
#  IC\u8868\u793A\u4E3AIdeaCommunity,https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-types.html#IntelliJPlatformType
platformType=IC
platformVersion=2024.2
# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
#  \u5199\u6CD5\u8BF4\u660E\uFF1A\u5E74\u4EFD\u540E\u4E24\u4F4D + \u5927\u7248\u672C\u53F7 + \u5C0F\u6570\u70B9 + \u5C0F\u7248\u672C\u53F7
pluginSinceBuild=242
pluginUntilBuild=243.*

aliyunRepositories=http://maven.aliyun.com/nexus/content/repositories/jcenter